apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmi-1
  name: bmi-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmi-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bmi-1
    spec:
      containers:
        - env:
            - name: MICROSCANNER_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: MICROSCANNER_TOKEN
                  name: bmi-1-config-vaic
          image: gcr.io/proto-example-bmi/github.com/viltohmyst/porto-example-bmi
          imagePullPolicy: IfNotPresent
          name: porto-example-bmi-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: bmi-1
  name: bmi-1-hpa-utsw
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bmi-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bmi-1
  name: bmi-1-service
  namespace: default
spec:
  clusterIP: 10.8.14.203
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31792
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: bmi-1
  sessionAffinity: None
  type: LoadBalancer